local addonName, ns = ...

-- One entry per item. Shape:
-- {
--     itemID     = 12345,
--     bonusIDs   = { 6654 },          -- from the wowhead bonus= param; used only for the hyperlink/dressup/chat-link
--     classes    = { "WARRIOR" },     -- classFiles that can loot this (from Wowhead's spec-restriction list), or nil if unrestricted
--     sourceType = "Dungeon",        -- "Dungeon" | "Quest" | "World" | "PvP"
--     source     = "Deadmines",      -- zone/instance/category
--     note       = "...",            -- short note shown under source
--     ilvl       = 23,               -- exact twink-scaled item level
--     armor      = 17,               -- armor value at that scaling, or nil for non-armor
--     sockets    = 2,                -- socket count at that scaling
--     socketTypes = { "prismatic" }, -- socket type per gem slot
--     socketBonus = { key = "vers", value = 1 }, -- CONDITIONAL "match the socket colors" bonus, not a guaranteed stat
--     stats      = { crit = 8 },     -- flat stat values at that scaling
-- }
-- Harvested from https://forsaken.ucoz.net/publ/guides/actual_equip/1-1-0-1
-- All numbers scraped with a real headless-Chromium pass over Wowhead (not plain HTML fetch) -
-- these items resolve their final ilvl/sockets/stats via client-side JS, so a static-HTML
-- fetch alone was giving wrong values for a meaningful chunk of items.
ns.Items = {
    { itemID = 27492, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Кузня Крови", note = "бисовые кожаные поножи", ilvl = 23, armor = 9, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { agi = 7, int = 7, stam = 10, crit = 6, vers = 6 } },
    { itemID = 24395, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Кузня Крови", note = "хороший тканевый пояс", ilvl = 23, armor = 3, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { int = 5, stam = 7, crit = 3, vers = 4 } },
    { itemID = 24388, bonusIDs = { 6710, 6652, 8810 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Кузня Крови", note = "бисовый кольчужный пояс", ilvl = 23, armor = 8, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "int", value = 1 }, stats = { agi = 5, int = 5, stam = 7, vers = 6 } },
    { itemID = 24393, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Кузня Крови", note = "лучшие тканевые руки на версу", ilvl = 23, armor = 3, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { int = 5, stam = 7, vers = 4 } },
    { itemID = 27531, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Разрушенные залы", note = "хорошие кожаные руки для критовиков (1/2 сета Странника пустошей)", ilvl = 23, armor = 6, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = nil, stats = { agi = 5, int = 5, stam = 7 } },
    { itemID = 27528, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Разрушенные залы", note = "бисовые кольчужные руки", ilvl = 23, armor = 8, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = nil, stats = { agi = 5, int = 5, stam = 7, crit = 5, haste = 5 } },
    { itemID = 29348, bonusIDs = { 6710, 6652 }, classes = { "WARRIOR", "HUNTER", "ROGUE", "SHAMAN", "MONK", "DRUID", "DEMONHUNTER" }, sourceType = "Dungeon", source = "Разрушенные залы", note = "кистевое, статов нет - только прок: +61 к скорости на 10 сек. при ударе (КД 45с)", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = {  } },
    { itemID = 28124, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Узилище", note = "бисовый кожаный пояс", ilvl = 23, armor = 6, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = nil, stats = { agi = 5, int = 5, stam = 7, crit = 5 } },
    { itemID = 24365, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Узилище", note = "хорошие кожаные руки на ловкачей", ilvl = 23, armor = 6, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { agi = 5, int = 5, stam = 7, crit = 4 } },
    { itemID = 27713, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Узилище", note = "бисовые кольчужные плечи", ilvl = 23, armor = 10, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { agi = 5, int = 5, stam = 7, crit = 6, haste = 5 } },
    { itemID = 24452, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Нижетопь", note = "хорошие кожаные руки на кастеров", ilvl = 23, armor = 6, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "int", value = 1 }, stats = { agi = 5, int = 5, stam = 7, vers = 3 } },
    { itemID = 24450, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Нижетопь", note = "хорошие тканевые руки для DPS", ilvl = 23, armor = 3, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { int = 5, stam = 7, crit = 5, haste = 3 } },
    { itemID = 24465, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Нижетопь", note = "бисовый кольчужный нагрудник", ilvl = 23, armor = 15, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "agi", value = 1 }, stats = { agi = 7, int = 7, stam = 10, crit = 7, haste = 7 } },
    { itemID = 24458, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Нижетопь", note = "бисовый латный ремень", ilvl = 23, armor = 13, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { str = 5, int = 5, stam = 7, crit = 5, vers = 3 } },
    { itemID = 24457, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Нижетопь", note = "бисовые латные плечи", ilvl = 23, armor = 15, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { str = 5, int = 5, stam = 7, crit = 6 } },
    { itemID = 30543, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Паровое подземелье", note = "бисовые тканевые ноги с силой заклинаний", ilvl = 23, armor = 5, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "int", value = 1 }, stats = { int = 7, stam = 10, vers = 7 } },
    { itemID = 27409, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Аукенайские гробницы", note = "хорошая кожаная голова", ilvl = 23, armor = 8, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { agi = 7, int = 7, stam = 10, crit = 5, vers = 5 } },
    { itemID = 27408, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Аукенайские гробницы", note = "хорошая латная голова на крит", ilvl = 23, armor = 17, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { str = 7, int = 7, stam = 10, crit = 13 } },
    { itemID = 27411, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Аукенайские гробницы", note = "бисовые тканевые ступни", ilvl = 23, armor = 4, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = nil, stats = { int = 5, stam = 7, vers = 5 } },
    { itemID = 27837, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Гробницы маны", note = "хорошие кожаные ноги для критовиков (1/2 сета Странника пустошей)", ilvl = 23, armor = 9, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = nil, stats = { agi = 7, int = 7, stam = 10, crit = 6 } },
    { itemID = 25942, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Гробницы маны", note = "бисовые латные руки", ilvl = 23, armor = 13, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { str = 5, int = 5, stam = 7, crit = 6, haste = 3 } },
    { itemID = 27986, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR", "HUNTER" }, sourceType = "Dungeon", source = "Сетеккские залы", note = "очень сильная двуручка для силовиков и сурв-хантов", ilvl = 23, armor = nil, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "stam", value = 2 }, stats = { str = 7, agi = 7, stam = 10, crit = 10 } },
    { itemID = 27901, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "ROGUE", "PALADIN", "MONK", "SHAMAN", "WARRIOR" }, sourceType = "Dungeon", source = "Темный лабиринт", note = "очень сильная одноручка для ловкачей и силовиков", ilvl = 23, armor = nil, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { str = 3, agi = 3 } },
    { itemID = 27775, bonusIDs = { 6710 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Темный лабиринт", note = "бисовые тканевые плечи", ilvl = 23, armor = 4, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "int", value = 1 }, stats = { int = 5, stam = 7, vers = 6 } },
    { itemID = 28230, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Темный лабиринт", note = "бисовая тканевая грудь с выносливостью", ilvl = 23, armor = 6, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "stam", value = 2 }, stats = { int = 7, stam = 10, vers = 8 } },
    { itemID = 28339, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Ботаника", note = "хорошие кожаные сапоги", ilvl = 23, armor = 6, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { agi = 5, int = 5, stam = 7, crit = 6 } },
    { itemID = 28348, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Ботаника", note = "хорошая кожаная голова с особым гнездом", ilvl = 23, armor = 8, sockets = 3, socketTypes = { "meta", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { agi = 7, int = 7, stam = 10, haste = 4, vers = 7 } },
    { itemID = 28229, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Ботаника", note = "бисовая тканевая грудь с интеллектом", ilvl = 23, armor = 6, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "int", value = 1 }, stats = { int = 7, stam = 10, crit = 2, vers = 7 } },
    { itemID = 28202, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Механар", note = "бисовый кожаный нагрудник", ilvl = 23, armor = 10, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { agi = 7, int = 7, stam = 10, crit = 4, vers = 7 } },
    { itemID = 28218, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Старые предгорья Хилсбрада", note = "бисовые тканевые поножи с выносливостью", ilvl = 23, armor = 5, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "stam", value = 2 }, stats = { int = 7, stam = 10, vers = 7 } },
    { itemID = 27434, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Старые предгорья Хилсбрада", note = "бисовые кожаные плечи", ilvl = 23, armor = 7, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = nil, stats = { agi = 5, int = 5, stam = 7, crit = 7, haste = 7 } },
    { itemID = 28224, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Старые предгорья Хилсбрада", note = "бисовая кожаная голова для критовиков (1/2 сета Странника пустошей)", ilvl = 23, armor = 8, sockets = 3, socketTypes = { "meta", "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { agi = 7, int = 7, stam = 10, crit = 7, haste = 5 } },
    { itemID = 30534, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Старые предгорья Хилсбрада", note = "бисовые кольчужные поножи", ilvl = 23, armor = 13, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { agi = 7, int = 7, stam = 10, crit = 7, haste = 8, vers = 4 } },
    { itemID = 30536, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Старые предгорья Хилсбрада", note = "бисовые латные поножи", ilvl = 23, armor = 20, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { str = 7, int = 7, stam = 10, crit = 7, haste = 5 } },
    { itemID = 34697, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "бисовые тканевые наручи на скорость", ilvl = 23, armor = 3, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "int", value = 0 }, stats = { int = 4, stam = 6, haste = 5 } },
    { itemID = 34793, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "лучший тканевый ремень на версу", ilvl = 23, armor = 3, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { int = 5, stam = 7, vers = 5 } },
    { itemID = 34602, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "DRUID" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "бисовые кожаные наручи", ilvl = 23, armor = 5, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { agi = 4, int = 4, stam = 6, vers = 4 } },
    { itemID = 34698, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "бисовые кольчужные наручи", ilvl = 23, armor = 7, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { agi = 4, int = 4, stam = 6, crit = 3, haste = 5 } },
    { itemID = 34789, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "бисовые латные наручи", ilvl = 23, armor = 11, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "str", value = 2 }, stats = { str = 4, int = 4, stam = 6, crit = 5 } },
    { itemID = 34795, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "хорошая латная голова на универсальность", ilvl = 23, armor = 17, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { str = 7, int = 7, stam = 10, vers = 8 } },
    { itemID = 34615, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "бисовый латный нагрудник", ilvl = 23, armor = 22, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { str = 7, int = 7, stam = 10, crit = 7, haste = 4 } },
    { itemID = 34807, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "бисовые латные сапоги", ilvl = 23, armor = 14, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { str = 5, int = 5, stam = 7, crit = 5 } },
    { itemID = 34601, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "лучшие латные плечи на скорость", ilvl = 23, armor = 15, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { str = 5, int = 5, stam = 7, haste = 5 } },
    { itemID = 34608, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "EVOKER", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Терраса Магистров", note = "лучший посох на кастеров", ilvl = 23, armor = nil, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { int = 30, stam = 10, vers = 10 } },
    { itemID = 37167, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Нексус", note = "хорошие кольчужные сапоги", ilvl = 23, armor = 9, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "stam", value = 1 }, stats = { agi = 5, int = 5, stam = 7, crit = 4, haste = 5 } },
    { itemID = 36945, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Окулус", note = "бисовые тканевые наручи на универсальность", ilvl = 23, armor = 3, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "vers", value = 1 }, stats = { int = 4, stam = 6, vers = 4 } },
    { itemID = 37237, rank = 1, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Азжол-Неруб", note = "бисовый латный шлем с особым гнездом", ilvl = 23, armor = 17, sockets = 3, socketTypes = { "meta", "prismatic", "prismatic" }, socketBonus = { key = "str", value = 1 }, stats = { str = 7, int = 7, stam = 10, crit = 8 } },
    { itemID = 37684, rank = 1, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Очищение Стратхольма", note = "бисовый тканевый шлем", ilvl = 23, armor = 4, sockets = 3, socketTypes = { "meta", "prismatic", "prismatic" }, socketBonus = { key = "haste", value = 8 }, stats = { int = 7, stam = 10, vers = 8 } },
    { itemID = 50214, bonusIDs = { 6710, 6652, 8810 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Кузня Душ", note = "бисовый кольчужный шлем", ilvl = 23, armor = 11, sockets = 3, socketTypes = { "meta", "prismatic", "prismatic" }, socketBonus = { key = "haste", value = 8 }, stats = { agi = 6, int = 6, stam = 8, crit = 5, haste = 7 } },
    { itemID = 49804, bonusIDs = { 6710, 6652, 8810 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Dungeon", source = "Яма Сарона", note = "хороший кольчужный шлем, но даёт меньше стат", ilvl = 23, armor = 11, sockets = 3, socketTypes = { "meta", "prismatic", "prismatic" }, socketBonus = { key = "haste", value = 8 }, stats = { agi = 5, int = 5, stam = 9, haste = 4, vers = 6 } },
    { itemID = 11808, bonusIDs = { 6712, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Глубины Черной горы", note = "хороший тканевый шлем для хиллеров, первая часть \"манасета\"", ilvl = 26, armor = 5, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 7, stam = 10, vers = 14 } },
    { itemID = 13353, bonusIDs = { 6712, 6652 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Стратхольм", note = "хороший офф-хенд на интовиков", ilvl = 26, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { int = 11, stam = 5, haste = 4, vers = 3 } },
    { itemID = 13505, bonusIDs = { 6712, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Стратхольм", note = "сильная двуручка для силовиков", ilvl = 26, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { str = 7, stam = 10, vers = 14 } },
    { itemID = 17780, bonusIDs = { 6712 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Мародон", note = "хороший кинжал для интовиков", ilvl = 26, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { int = 20, stam = 5, haste = 3, vers = 4 } },
    { itemID = 17943, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST" }, sourceType = "Dungeon", source = "Мародон", note = "вторая часть \"манасета\", нужен хилам для регена маны", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { int = 19, stam = 5, crit = 3, haste = 3 } },
    { itemID = 9394, bonusIDs = { 6710, 6652, 8811 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Ульдаман", note = "забавный латный шлем для контроля противника в PvP", ilvl = 23, armor = 17, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 7, int = 7, stam = 10, haste = 13 } },
    { itemID = 119414, bonusIDs = { 572, 13619 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает интовикам с Хранитель рощи Йал в Горгронде", ilvl = 26, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 4, stam = 6, haste = 4, vers = 4 } },
    { itemID = 119349, bonusIDs = { 572, 13619 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "SHAMAN", "DRUID" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает ловкачам с Гиблет Трусливый на Хребте Ледяного Огня", ilvl = 26, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { agi = 4, stam = 6, vers = 4, iskus = 4 } },
    { itemID = 119351, bonusIDs = { 572, 13619 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает силовикам с Слякоч-повелитель в Горгронде", ilvl = 26, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, stam = 6, crit = 3, haste = 4 } },
    { itemID = 120317, bonusIDs = { 572, 13619 }, classes = { "DEMONHUNTER", "DEATHKNIGHT", "ROGUE", "PALADIN", "MONK", "SHAMAN", "DRUID", "WARRIOR" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает силовикам и ловкачам с Монстр арены в Награнде (В РЕЖИМЕ ИСТОРИИ)", ilvl = 26, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, agi = 4, stam = 6, vers = 3, iskus = 4 } },
    { itemID = 119390, bonusIDs = { 572, 13619 }, classes = { "PALADIN", "SHAMAN", "WARRIOR" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает с Бармагрыз на Хребте Ледяного Огня", ilvl = 26, armor = 68, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 3, int = 11, stam = 5, crit = 3, vers = 4 } },
    { itemID = 119391, bonusIDs = { 572, 13619 }, classes = { "PALADIN", "SHAMAN", "WARRIOR" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает с Могамаго в Горгронде", ilvl = 26, armor = 68, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 3, int = 11, stam = 5, crit = 4, vers = 3 } },
    { itemID = 119399, bonusIDs = { 572, 13619 }, classes = { "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST" }, sourceType = "World", source = "Дренор (рарники, раз в день)", note = "падает с Сын Горамала на Хребте Ледяного Огня", ilvl = 26, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 20, stam = 5, crit = 3, vers = 4 } },
    { itemID = 158583, bonusIDs = { 4244, 8810 }, classes = { "WARRIOR", "HUNTER", "MAGE", "DRUID" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Дикобраз-матриарх в Друстваре", ilvl = 23, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, agi = 4, int = 4, stam = 6, crit = 5, iskus = 3 } },
    { itemID = 155571, bonusIDs = { 4244, 8810 }, classes = nil, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с сундука за доставку рарника Страж источника к нпс Чалый Бертольд на Тирагардском поморье", ilvl = 23, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, agi = 4, int = 4, stam = 6, haste = 2, iskus = 5 } },
    { itemID = 155572, bonusIDs = { 4244, 8810 }, classes = { "PALADIN", "PRIEST", "SHAMAN", "MONK", "DRUID", "ROGUE", "EVOKER", "WARLOCK", "DEMONHUNTER" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Мрачноморд Безмозглый в Долине Штормов (В РЕЖИМЕ ИСТОРИИ)", ilvl = 23, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, agi = 4, int = 4, stam = 6, haste = 4, vers = 4 } },
    { itemID = 155164, bonusIDs = { 4244, 8810 }, classes = { "DEATHKNIGHT", "ROGUE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Сестра Абсинтия в Долине Штормов (В РЕЖИМЕ ИСТОРИИ)", ilvl = 23, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, agi = 4, int = 4, stam = 6, crit = 3, vers = 4 } },
    { itemID = 160984, bonusIDs = { 4244, 8810 }, classes = { "PALADIN", "WARRIOR" }, sourceType = "World", source = "Зандалар (рарники, раз на персонажа)", note = "падает с Кандак в Зулдазаре", ilvl = 23, armor = 4, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 4, agi = 4, int = 4, stam = 6, crit = 4, vers = 4 } },
    { itemID = 160451, bonusIDs = { 6710, 6652, 8810 }, classes = { "ROGUE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Бармен Билл на Тирагардском поморье", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { agi = 3, stam = 5, crit = 4, haste = 3 } },
    { itemID = 159518, bonusIDs = { 6710, 6652, 8810 }, classes = { "ROGUE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Длинноклык и Генри Брейкуотер в Долине Штормов", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { agi = 3, stam = 5, haste = 3, iskus = 3 } },
    { itemID = 160952, bonusIDs = { 6710, 6652, 8810 }, classes = { "ROGUE" }, sourceType = "World", source = "Зандалар (рарники, раз на персонажа)", note = "падает с Кинжалозуб в Зулдазаре", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { agi = 3, stam = 5, crit = 3, haste = 3 } },
    { itemID = 154217, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Мак в Друстваре", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, iskus = 4, vers = 3 } },
    { itemID = 155278, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Чешуетряс Ядовитый на Тирагардском поморье", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, haste = 4, vers = 2 } },
    { itemID = 155425, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "EVOKER", "MONK", "SHAMAN", "DRUID" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Королева шипожалов в Друстваре", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, haste = 3, vers = 4 } },
    { itemID = 160958, bonusIDs = { 6710, 6652, 8810 }, classes = { "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST" }, sourceType = "World", source = "Зандалар (рарники, раз на персонажа)", note = "падает с Темноуст Джо'ла в Зулдазаре", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, crit = 3, iskus = 3 } },
    { itemID = 155273, bonusIDs = { 6710, 6652, 8810 }, classes = { "DEMONHUNTER", "EVOKER", "PALADIN", "MONK", "SHAMAN" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Пилозуб в Боралусе", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, crit = 3, vers = 4 } },
    { itemID = 155551, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Сквиргл-из-Глубин на Тирагардском поморье", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, crit = 4, vers = 3 } },
    { itemID = 155299, bonusIDs = { 6710, 6652, 8810 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Сестра Марта в Друстваре", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 19, stam = 5, haste = 4, iskus = 2 } },
    { itemID = 160447, bonusIDs = { 4776, 4802 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Эмили Мэйвилл в Друстваре", ilvl = 23, armor = nil, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { int = 10, stam = 5, haste = 3, vers = 4 } },
    { itemID = 160978, bonusIDs = { 6710, 6652, 8810 }, classes = { "PALADIN", "SHAMAN", "WARRIOR" }, sourceType = "World", source = "Зандалар (рарники, раз на персонажа)", note = "падает с Хакби Восставший в Зулдазаре", ilvl = 23, armor = 66, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 3, int = 10, stam = 5, crit = 3, vers = 3 } },
    { itemID = 158597, bonusIDs = { 6710, 6652, 8810 }, classes = { "PALADIN", "SHAMAN", "WARRIOR" }, sourceType = "World", source = "Кул-Тирас (рарники, раз на персонажа)", note = "падает с Кулетт Вспыльчивый на Тирагардском поморье", ilvl = 23, armor = 66, sockets = 1, socketTypes = { "prismatic" }, socketBonus = nil, stats = { str = 3, int = 10, stam = 5, haste = 2, iskus = 4 } },
    { itemID = 28177, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Quest", source = "Темный лабиринт", note = "здесь за квест дают бисовые сапоги на кольчугу Аукенайские сапоги и временные латы Скованные Ша'тар наголенники", ilvl = 23, armor = 9, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { agi = 5, int = 5, stam = 7, vers = 8 } },
    { itemID = 29337, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "Quest", source = "Аукенайские гробницы", note = "за квест здесь дают начальный грудак для латников Защитник наместника", ilvl = 23, armor = 22, sockets = 3, socketTypes = { "prismatic", "prismatic", "prismatic" }, socketBonus = { key = "stam", value = 2 }, stats = { str = 7, int = 7, stam = 10, crit = 6 } },
    { itemID = 29319, bonusIDs = { 6710, 6652 }, classes = { "EVOKER", "HUNTER", "SHAMAN" }, sourceType = "Quest", source = "Старые предгорья Хилсбрада", note = "кольчужный ремень за сопровождение Тралла (парная награда к Касанию бури)", ilvl = 23, armor = 8, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "int", value = 1 }, stats = { agi = 5, int = 5, stam = 7, vers = 10 } },
    { itemID = 77530, bonusIDs = { 7175 }, classes = nil, sourceType = "Craft", source = "Инженерия", note = "крафт (инженерия), статы зависят от изготовления - самая популярная триальная тринька", ilvl = 18, armor = nil, sockets = 3, socketTypes = { "cogwheel", "cogwheel", "cogwheel" }, socketBonus = nil, stats = {  } },
    { itemID = 178769, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "ROGUE", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Чумные каскады", note = "лучшая тринька для фарма подземелий", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { agi = 6, int = 6 } },
    { itemID = 108902, bonusIDs = { 6710, 6652 }, classes = nil, sourceType = "World", source = "Долина Призрачной Луны", note = "прожимка на искусность (сама вещь на универсальность), с сокровища", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { vers = 9 } },
    { itemID = 109997, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "ROGUE", "MONK", "SHAMAN", "DRUID" }, sourceType = "Dungeon", source = "Железные доки", note = "аналог бивня на прожим искусности", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { agi = 5 } },
    { itemID = 110017, bonusIDs = { 6710, 6652 }, classes = nil, sourceType = "Dungeon", source = "Железные доки", note = "лучшая прожимка на универсальность", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { vers = 12 } },
    { itemID = 110002, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Железные доки", note = "лучшая прожимка на скорость", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { int = 5 } },
    -- Знак различия: одна и та же вещь, но у сторон разные itemID. Показывается
    -- только своя - поле faction отсеивает чужую.
    { itemID = 122371, faction = "Alliance", bonusIDs = {  }, classes = nil, sourceType = "PvP", source = "Фамильные вещи", note = "фамильная тринька для PvP", ilvl = 20, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { stam = 7 } },
    { itemID = 122370, faction = "Horde", bonusIDs = {  }, classes = nil, sourceType = "PvP", source = "Фамильные вещи", note = "фамильная тринька для PvP", ilvl = 20, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { stam = 7 } },
    { itemID = 116824, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "DRUID", "HUNTER", "MONK", "ROGUE", "SHAMAN" }, sourceType = "World", source = "Награнд", note = "[ДД] хороший прок ловкости; рарник, убивать В РЕЖИМЕ ИСТОРИИ", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { haste = 9 } },
    { itemID = 113163, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "DRUID", "HUNTER", "MONK", "ROGUE", "SHAMAN" }, sourceType = "Quest", source = "Долина Призрачной Луны", note = "[ДД] аналог Рога талбука, с квеста", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { vers = 9 } },
    { itemID = 113408, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "PALADIN", "WARRIOR" }, sourceType = "World", source = "Долина Призрачной Луны", note = "[ДД] хороший прок силы, с сокровища", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { haste = 9 } },
    { itemID = 137459, bonusIDs = { 6710, 6652 }, classes = nil, sourceType = "Dungeon", source = "Штурм Аметистовой крепости", note = "[ДД] последовательное накопление основной характеристики", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { haste = 9 } },
    { itemID = 159630, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Усадьба Уэйкрестов", note = "[ДД] хорошая прожимка на интеллект", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { iskus = 9 } },
    { itemID = 28223, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Старые предгорья Хилсбрада", note = "[ДД] хорошая прожимка на силу заклинаний", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { crit = 7 } },
    { itemID = 137362, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "DEMONHUNTER", "DRUID", "MONK", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Око Азшары", note = "[Танк] спасает от критического урона", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { stam = 9 } },
    { itemID = 37220, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "DEMONHUNTER", "DRUID", "MONK", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Азжол-Неруб", note = "[Танк] пассивно снижает получаемый урон, очень хороша на аое запулах", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { stam = 10 } },
    { itemID = 137344, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "DEMONHUNTER", "DRUID", "MONK", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Логово Нелтариона", note = "[Танк] прожимка, снижающая получаемый урон", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { vers = 9 } },
    { itemID = 27770, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "DEMONHUNTER", "DRUID", "MONK", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Нижетопь", note = "[Танк] нишевая смесь Квинтэссенции и Скаломола", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { stam = 7 } },
    { itemID = 56370, bonusIDs = { 6710, 6652 }, classes = { "DEATHKNIGHT", "DEMONHUNTER", "DRUID", "MONK", "PALADIN", "WARRIOR" }, sourceType = "Dungeon", source = "Вершина Смерча", note = "[Танк] сильно увеличивает запас здоровья; нужно засумониться в данж 30 уровня", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { vers = 9 } },
    { itemID = 88360, bonusIDs = { 6710, 6652 }, classes = { "DEMONHUNTER", "WARLOCK", "EVOKER", "PALADIN", "MONK", "SHAMAN", "DRUID", "PRIEST", "MAGE" }, sourceType = "Dungeon", source = "Некроситет", note = "[Хил] реген маны", ilvl = 23, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { int = 6 } },

    -- Шеи с суммой вторичных статов >=19 - собраны и сверены живыми тултипами
    -- в этой сессии (не через форс ilvl на Wowhead, который для контента после
    -- Wrath оказался ненадёжным - см. переписку). bonusIDs пустые: как и у
    -- других вещей из Стратхольма/Мародона выше, весь сквош до 20 уровня даёт
    -- само поле linkLevel в BuildItemLink, отдельный bonus для этого не нужен.
    { itemID = 39487, bonusIDs = { 6712, 6652 }, classes = { "HUNTER" }, sourceType = "Quest", source = "Низина Шолазар", note = "бисовый лук за цепочку Хеминга Эрнестуэя, вторичек вдвое больше, чем у других пушек", ilvl = 26, armor = nil, sockets = 0, socketTypes = {  }, socketBonus = nil, stats = { agi = 7, stam = 10, crit = 13, haste = 18 } },
    { itemID = 29317, bonusIDs = { 6710, 6652 }, classes = { "WARLOCK", "PRIEST", "MAGE" }, sourceType = "Quest", source = "Старые предгорья Хилсбрада", note = "тканевые руки за сопровождение Тралла (парная награда к Кушаку поборника)", ilvl = 23, armor = 3, sockets = 2, socketTypes = { "prismatic", "prismatic" }, socketBonus = { key = "crit", value = 1 }, stats = { int = 5, stam = 7, crit = 3, vers = 2 } },
}
